### ISSUE TITLE
Multiple PartnerOrg Issue

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#473]
When we have tried to add PartnerOrgs through Houston, it is at first confusing to know which collection to add to, since there are two: 
![partnerorg1](https://user-images.githubusercontent.com/7898004/29234826-c274939c-7ec7-11e7-8232-afc16aa569e2.png)
In the past, when we've selected one to edit, it does not work perfectly. The changes don't seem to hold. Deleting an org seemed to cause some sort of glitch that then worked itself out, but now we have two partners as "Boston Promise Initiative/DSNI"
<img width="1035" alt="screen shot 2017-08-11 at 7 01 09 pm" src="https://user-images.githubusercontent.com/7898004/29234848-f720a7ca-7ec7-11e7-9f2c-342fcb3d7858.png">

Lastly, where this shows up in production, in admin, or on member signup, the partners listed do not come in alphabetical order, which is a bit confusing! 
<img width="416" alt="screen shot 2017-08-11 at 7 01 35 pm" src="https://user-images.githubusercontent.com/7898004/29234854-13d7b110-7ec8-11e7-9601-abed946c9277.png">

**Comment by drenfr01** [comment]
@ballek This is such a well-written ticket! I might frame it in my office :)

**Comment by drenfr01** [comment]
this should be fixed, and I hid some collections in the Admin portal that aren't relevant.

**Comment by ballek** [comment]
@drenfr01 i'm simply doing what any bug squasher would ;)

**Comment by ballek** [comment]
<img width="389" alt="screen shot 2017-09-28 at 12 37 49 pm" src="https://user-images.githubusercontent.com/7898004/30978891-f28b9ca4-a449-11e7-9af8-33b2e7163d24.png">
Alphabetization looks great! 

I'm still seeing two partnerOrganizations collections in Houston... and here's something really confusing, when i began they both had 22 items. I then deleted **one** of the BPI/DSNIs and now one collection has only 20 items!!!!!

<img width="748" alt="screen shot 2017-09-28 at 12 38 01 pm" src="https://user-images.githubusercontent.com/7898004/30978956-1e9855bc-a44a-11e7-8d31-bb04f5b221f0.png">

**Comment by drenfr01** [comment]
@ballek Well excellent bug squashing! Also, I totally believe you, but when I check the Houston screen now on Prod I only see 1 partnerOrganizations collection with 22 entries. There were two BPI/DSNIs, and oddly enough when I deleted one it went down to 20 entries. However, I manually counted the entires after the deletion and it adds up to 20 with only one DSNI.

I checked the fixture data, and we're not adding duplicates, so I'm a bit of a loss here. Can you check on your side and see what it looks like now?

**Comment by drenfr01** [comment]
ready for testing in Prod as of October 2 @ 10:30 pm EST

**Comment by ballek** [comment]
<img width="859" alt="screen shot 2017-10-02 at 10 58 04 pm" src="https://user-images.githubusercontent.com/7898004/31108179-9d3f50b8-a7c5-11e7-8cb4-7800ae61faf6.png">

alas!

**Comment by drenfr01** [comment]
@ballek this might be a caching issue, because I just checked prod on a separate laptop and it still shows only the one collection. Can you try checking on an incognito window?

**Comment by ballek** [comment]
@drenfr01 you're a GENIUS
